- name: Demo on Vars
  hosts: all

# vars_files:
#   - example-vars.yml   
 # vars:
  #  URL: play.example.com
   # PROJECT: example
  #vars_prompt:  
   # - name: URL
    #  prompt: Enter URL
     # private: no
  tasks:
    - name: Print URL
      debug:
        msg: URL = {{ URL }}
    - name: Print URL
      debug:
        msg: URL = {{ URL }}
      vars:
        URL: task.example.com
# Variable Precedence
# command line vars with -e 
# Tasks
# vars_files
# vars_prompt
# vars
# iventary vars

- name: Demo on Dynamic Vars
  hosts: NEW
  tasks:
    - name: Gather date
      shell: date +%F
      register: out
    - name: Print Date
      debug:
        msg: Date = {{ out }}  

