- name: Demo on Vars
  hosts: all
  vars:
    URL: play.example.com
    PROJECT: example
  tasks:
    - name: Print URL
      debug:
        msg: URL = {{ URL }}
    -name: Print URL
      debug:
        msg: URL = {{ URL }}
      vars:
        URL: task.example.com


           