- name: Demo on loop
  hosts: all
  tasks:
    - name: print fruitnames
      debug:
        msg: "Fruit = {{ item }}"
      loop:
        - banana
        - apple
        - orange
    - name: Create servers
      debug:
        msg: "{{ item.name }}"
      loop:
        - name: server1
          disk: 3gb
          ram: 15gb
          network:
            nic01: 100gb
            nic02: 10gb

        - name: server2
          disk: 3gb
          ram: 15gb
          network:
            nic01: 100gb
            nic02: 10gb  
      loop_control:
         label: "{{ item.name }}"        

    - name: Count out fruit
      ansible.builtin.debug:
        msg: "{{ item }} with index {{ my_idx}}""
      loop:
        - apple
        - banana
        - pear
      loop_control:
        index_var: my_idx
