- name: Demo on loop
  hosts: all
  tasks:
    - name: print fruitnames
      debug:
        msg: "Fruit = {{ item }}"
      loop:
        - banana
        - apple
        - orange
    - name: Create servers
      debug:
        msg: "{{ item.name }}"
      loop:
        - name: server1
          disk: 3gb
          ram: 15gb
          network:
            nic01: 100gb
            nic02: 10gb

        - name: server2
          disk: 3gb
          ram: 15gb
          network:
            nic01: 100gb
            nic02: 10gb  
      loop_control:
         label: "{{ item.name }}"        

    - name: Count out fruit
      debug:
        msg: "{{ item }} with index {{ my_idx }}"
      loop:
        - apple
        - banana
        - pear
      loop_control:
        index_var: my_idx

    - name: Loop variable
      debug:
        msg: "{{ myvar }}"
      loop:
        - apple
        - banana
        - pear
      loop_control:
        loop_var: myvar

    - name: print first value
      #when: ansible_loop.first
      debug:
        msg: "{{ ansible_loop.first }}"
      loop:
        - apple
        - banana
        - pear
      loop_control:
        extended: yes  

