- name: setup roboshop project
  hosts: all
  become: yes
  ## THIS become can also be useer at task level
  tasks:
    - name: Install Nginx
      apt:
       name: nginx
       update_cache: yes
       state: present

    - name: Start Nginx
      systemd:
        state: started
        name: nginx
        enabled:yes


    